platform :ios, '9.0'

target 'JSON Assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JSON Assignment
	pod 'CollectionViewPagingLayout'
	pod 'Charts'
	pod 'TinyConstraints'
end
